### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by SpencerBrown** [VladRassokhin/intellij-hcl#11]
Just updated plugin to 4.0

Immediately upon opening my project I get:

8:56:47 AM ClassCastException: org.intellij.plugins.hcl.terraform.il.psi.impl.ILLiteralExpressionImpl cannot be cast to org.intellij.plugins.hcl.terraform.il.psi.ILVariable

This did not happen previously.

Details:

org.intellij.plugins.hcl.terraform.il.psi.impl.ILLiteralExpressionImpl cannot be cast to org.intellij.plugins.hcl.terraform.il.psi.ILVariable
java.lang.ClassCastException: org.intellij.plugins.hcl.terraform.il.psi.impl.ILLiteralExpressionImpl cannot be cast to org.intellij.plugins.hcl.terraform.il.psi.ILVariable
	at org.intellij.plugins.hcl.terraform.il.psi.impl.TILPsiImplUtils.getField(TILPsiImplUtils.kt:97)
	at org.intellij.plugins.hcl.terraform.il.psi.impl.TILPsiImplUtilJ.getField(TILPsiImplUtilJ.java:76)
	at org.intellij.plugins.hcl.terraform.il.psi.impl.ILSelectExpressionImpl.getField(ILSelectExpressionImpl.java:33)
	at org.intellij.plugins.hcl.terraform.il.psi.ILSelectFromSomethingReferenceProviderKt.getGoodLeftElement(ILSelectFromSomethingReferenceProvider.kt:110)
	at org.intellij.plugins.hcl.terraform.il.psi.ILSelectFromSomethingReferenceProvider.getReferencesByElement(ILSelectFromSomethingReferenceProvider.kt:45)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:124)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:70)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:61)
	at org.intellij.plugins.hcl.terraform.il.psi.impl.ILExpressionWithReference.getReferences(ILExpressionWithReference.kt:26)
	at org.intellij.plugins.intelliLang.references.InjectedReferencesContributor.getInjectedReferences(InjectedReferencesContributor.java:55)
	at org.intellij.plugins.intelliLang.references.InjectedReferencesInspection$1.visitElement(InjectedReferencesInspection.java:38)
	at org.intellij.plugins.hcl.terraform.il.psi.impl.ILExpressionBase.accept(ILExpressionBase.kt:35)
	at org.intellij.plugins.hcl.terraform.il.psi.impl.ILVariableImpl.accept(ILVariableImpl.java:24)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:687)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$1100(LocalInspectionsPass.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$6.process(LocalInspectionsPass.java:347)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$6.process(LocalInspectionsPass.java:344)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:211)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:140)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

**Comment by VladRassokhin** [comment]
Looks like you have interpolation which looks like `${aws_instance.x."string".ref}`, note quoted string. 
Is Terraform parses that ok?

Anyway will release fix ASAP.

**Comment by SpencerBrown** [comment]
I believe you're asking, can the index be a string (vs. an integer) when referring to one of a multiple reference in an interpolation?

I believe the answer is "yes". Terraform's HCL is pretty strange in places, and not well documented. I had no problems with Terraform parsing my .tf files.

**Comment by VladRassokhin** [comment]
Yep, asking. Just woke up, still cannot think clear :)
Actually problem was with numbers in selects like: `${a.b.10.c}`
Released version 0.4.1 with fix.

**Comment by SpencerBrown** [comment]
No more crash!  Thanks for the super fast response!
