### ISSUE TITLE
IDE Exception: java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by MastaPA** [VladRassokhin/intellij-hcl#182]
I'm getting IDE Exception when using interpolation syntax where more than four nested items

### Installation details
 - [ ] IntelliJ IDEA 2018.3.1 (Community Edition)
Build #IC-183.4588.61, built on December 4, 2018
JRE: 1.8.0_152-release-1343-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2
 - [ ] intellij-hcl plugin version v0.6.12
 - [ ] Terraform version  v0.11.10

### Terraform Configuration Files
```
resource "google_dataproc_cluster" "dataproc_cluster" {
  name = "cluster"
  region = "us-east1"

  cluster_config {
    master_config {
      num_instances = 1
      machine_type = "n1-standard-1"
      disk_config {
        boot_disk_size_gb = 10
        num_local_ssds = 0
      }
    }
    worker_config {
      num_instances = 2
      machine_type = "n1-standard-1"
      disk_config {
        boot_disk_size_gb = 10
        num_local_ssds = 1
      }
    }
  }
}

output "master_name" {
  value = "${google_dataproc_cluster.dataproc_cluster.cluster_config.master_config.instance_names}"
}
```

Exception appears after entering . after fours element (master_config)
### Exception
```text
java.lang.UnsupportedOperationException
	at org.intellij.plugins.hil.psi.FakeHCLProperty.getValue(FakeHCLProperty.kt:33)
	at org.intellij.plugins.hil.codeinsight.HILCompletionContributor$SelectCompletionProvider.getPropertyObjectProperties(HILCompletionContributor.kt:345)
	at org.intellij.plugins.hil.codeinsight.HILCompletionContributor$SelectCompletionProvider.addCompletions(HILCompletionContributor.kt:319)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:87)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:96)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:87)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:63)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:827)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:812)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:272)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:169)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:269)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
### Expected Behavior
I expected to get autocomplete prompt to chose output element
 
### Actual Behavior
It doesn't happen.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create output with more than four nested elements
2. Enter . 
3. You'll see exception

**Comment by VladRassokhin** [comment]
Actually it's not because it's forth element but nature of 'master_config' blocks which are marked as 'computed' in schema and bug in plugin code.

**Comment by MastaPA** [comment]
I didn't understand clearly from your comment is it bug in plugin or not

**Comment by VladRassokhin** [comment]
It was a bug in plugin, but it's not related to some exact number of elements ;)

**Comment by MastaPA** [comment]
Got it, thank you. Keep doing all this great stuff. Thank you once more
