### ISSUE TITLE
IDE Exception in Plugin

### ISSUE THREAD

**Issue by rbizzell40** [VladRassokhin/intellij-hcl#186]
Thank you for opening an issue.
In this template paragraph text could be removed, however please retain headers.

### Prerequisites
 - [ ] Ensure you have latest version of plugin installed
 - [ ] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
 - [ ] intellij-hcl plugin version (`Settings->Plugins`)
 - [ ] Terraform version (`terraform -v`)

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configuration here - for large Terraform configs,
# please use a gist (https://gist.github.com) and share a link. 
```

### Exception
```text
For exceptions paste exception stack trace here. If it's huge one - use gist.
```

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Place cursor somewhere
2. Invoke completion.

**Comment by rbizzell40** [comment]
ollowing exceptions happened soon after this one, most probably they are induced.


2019-01-03T10:36:52.923
java.lang.NoClassDefFoundError: com/beust/klaxon/Parser
	at org.intellij.plugins.hcl.terraform.config.model.TypeModelLoader$Companion.getResourceJson(TypeModelLoader.kt:140)
	at org.intellij.plugins.hcl.terraform.config.model.TypeModelLoader$Companion.getModelExternalInformation(TypeModelLoader.kt:133)
	at org.intellij.plugins.hcl.terraform.config.model.TypeModelProvider.loadExternalInformation(TypeModelProvider.kt:73)
	at org.intellij.plugins.hcl.terraform.config.model.TypeModelProvider.access$loadExternalInformation(TypeModelProvider.kt:29)
	at org.intellij.plugins.hcl.terraform.config.model.TypeModelProvider$external$2.invoke(TypeModelProvider.kt:33)
	at org.intellij.plugins.hcl.terraform.config.model.TypeModelProvider$external$2.invoke(TypeModelProvider.kt:29)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.intellij.plugins.hcl.terraform.config.model.TypeModelProvider.getExternal(TypeModelProvider.kt)
	at org.intellij.plugins.hcl.terraform.config.model.TypeModelProvider$_model$2.invoke(TypeModelProvider.kt:31)
	at org.intellij.plugins.hcl.terraform.config.model.TypeModelProvider$_model$2.invoke(TypeModelProvider.kt:29)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.intellij.plugins.hcl.terraform.config.model.TypeModelProvider.get_model(TypeModelProvider.kt)
	at org.intellij.plugins.hcl.terraform.config.model.TypeModelProvider.access$get_model$p(TypeModelProvider.kt:29)
	at org.intellij.plugins.hcl.terraform.config.model.TypeModelProvider$Companion.getModel(TypeModelProvider.kt:46)
	at org.intellij.plugins.hcl.terraform.config.codeinsight.ModelHelper.getTypeModel(TerraformConfigCompletionContributor.kt:700)
	at org.intellij.plugins.hcl.terraform.config.codeinsight.ModelHelper.getProviderProperties(TerraformConfigCompletionContributor.kt:607)
	at org.intellij.plugins.hcl.terraform.config.codeinsight.ModelHelper.getBlockProperties(TerraformConfigCompletionContributor.kt:574)
	at org.intellij.plugins.hcl.terraform.config.inspection.HCLBlockMissingPropertyInspection$MyEV.visitBlock(HCLBlockMissingPropertyInspection.kt:71)
	at org.intellij.plugins.hcl.psi.impl.HCLBlockImpl.accept(HCLBlockImpl.java:21)
	at org.intellij.plugins.hcl.psi.impl.HCLBlockImpl.accept(HCLBlockImpl.java:25)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:292)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:260)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$6(LocalInspectionsPass.java:257)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1163)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:65)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:56)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:263)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:196)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:115)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by VladRassokhin** [comment]
Please fill issue template (first message) or remove it.
Looks like you have broken plugin distribution, how had you installed plugin?
Reinstall should solve problem.

**Comment by rbizzell40** [comment]
Installed plugin from disk

**Comment by rbizzell40** [comment]
I reinstalled it just now

**Comment by VladRassokhin** [comment]
>Installed plugin from disk

Where did you get plugin zip initially?

**Comment by rbizzell40** [comment]
Jetbrains download

**Comment by VladRassokhin** [comment]
Closing as incorrectly formatted
