### ISSUE TITLE
AE on editing injected fragment

### ISSUE THREAD

**Issue by VladRassokhin** [VladRassokhin/intellij-hcl#20]
```text
Assertion failed
java.lang.AssertionError: Assertion failed
	at org.intellij.plugins.hcl.psi.impl.HCLStringLiteralMixin.updateText(HCLStringLiteralMixin.kt:88)
	at org.intellij.plugins.hcl.psi.HCLStringLiteralManipulator.handleContentChange(HCLStringLiteralManipulator.kt:27)
	at org.intellij.plugins.hcl.psi.HCLStringLiteralManipulator.handleContentChange(HCLStringLiteralManipulator.kt:23)
	at com.intellij.codeInsight.intention.impl.QuickEditHandler.b(QuickEditHandler.java:420)
	at com.intellij.codeInsight.intention.impl.QuickEditHandler.access$1000(QuickEditHandler.java:83)
	at com.intellij.codeInsight.intention.impl.QuickEditHandler$8.run(QuickEditHandler.java:375)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect$3.compute(PostprocessReformattingAspect.java:115)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:124)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:112)
	at com.intellij.codeInsight.intention.impl.QuickEditHandler.a(QuickEditHandler.java:368)
	at com.intellij.codeInsight.intention.impl.QuickEditHandler.documentChanged(QuickEditHandler.java:276)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:774)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:713)
	at com.intellij.openapi.editor.impl.DocumentImpl.insertString(DocumentImpl.java:468)
	at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaretNoScrolling(EditorModificationUtil.java:131)
	at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaret(EditorModificationUtil.java:96)
	at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaret(EditorModificationUtil.java:88)
	at com.intellij.openapi.editor.EditorModificationUtil.typeInStringAtCaretHonorBlockSelection(EditorModificationUtil.java:325)
	at com.intellij.codeInsight.editorActions.TypedHandler.a(TypedHandler.java:240)
	at com.intellij.codeInsight.editorActions.TypedHandler.access$100(TypedHandler.java:63)
	at com.intellij.codeInsight.editorActions.TypedHandler$1.perform(TypedHandler.java:204)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:345)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:425)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:336)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:327)
	at com.intellij.codeInsight.editorActions.TypedHandler.execute(TypedHandler.java:148)
	at com.intellij.codeInsight.lookup.impl.LookupTypedHandler.execute(LookupTypedHandler.java:90)
	at com.intellij.codeInsight.editorActions.AutoFormatTypedHandler.b(AutoFormatTypedHandler.java:167)
	at com.intellij.codeInsight.editorActions.AutoFormatTypedHandler.execute(AutoFormatTypedHandler.java:94)
	at com.goide.editor.GoTypedHandler.execute(GoTypedHandler.java:39)
	at com.intellij.openapi.editor.actionSystem.TypedAction$DefaultRawHandler$1$1.run(TypedAction.java:153)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1009)
	at com.intellij.openapi.editor.actionSystem.TypedAction$DefaultRawHandler$1.run(TypedAction.java:147)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.editor.actionSystem.TypedAction$DefaultRawHandler.execute(TypedAction.java:139)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:133)
	at com.intellij.openapi.editor.impl.EditorImpl.b(EditorImpl.java:1165)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:5481)
	at com.intellij.openapi.editor.impl.EditorImpl$9.keyTyped(EditorImpl.java:996)
	at java.awt.Component.processKeyEvent(Component.java:6490)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
	at java.awt.Component.processEvent(Component.java:6312)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4762)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:632)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


```
Affected version: 0.5.0

**Comment by VladRassokhin** [comment]
Workaround: avoid editing injected fragments in separate editors.

**Comment by VladRassokhin** [comment]
Happened for HIL injection in `"text"` string after adding quotes/other symbols before/after last quote.
