### ISSUE TITLE
Exception  #decode was not called or returned 'false'

### ISSUE THREAD

**Issue by voron** [VladRassokhin/intellij-hcl#203]
I see exception when typing new line `\n` after HCL interpolation `${}`

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
```
IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019
JRE: 1.8.0_202-release-1483-b44 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4
```
 - [x] intellij-hcl plugin version (`Settings->Plugins`)
v0.6.14
 - [x] Terraform version (`terraform -v`)
Terraform v0.11.11

### Terraform Configuration Files
```hcl
output "kibana_creds" {
  value = "Kibana URL: ${var.kibana_domain}\n 123"
  description = "Kibana URL and credentials"
  sensitive = true

  depends_on = [
    "helm_release.efk",
  ]
}
```

### Exception
```text
java.lang.IllegalStateException: #decode was not called or returned 'false'
	at org.intellij.plugins.hcl.psi.impl.HCLStringLiteralTextEscaper.getOffsetInHost(HCLStringLiteralTextEscaper.kt:38)
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.decode(InjectionRegistrarImpl.java:192)
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.reparse(InjectionRegistrarImpl.java:602)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.reparse(InjectedLanguageUtil.java:798)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.reparseChangedInjectedFragments(PsiDocumentManagerImpl.java:191)
	at com.intellij.psi.impl.DocumentCommitThread.doCommit(DocumentCommitThread.java:666)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$commitUnderProgress$4(DocumentCommitThread.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:453)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$pollQueue$1(DocumentCommitThread.java:281)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.psi.impl.DocumentCommitThread.pollQueue(DocumentCommitThread.java:281)
	at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.lambda$run$0(BoundedTaskExecutor.java:198)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Expected Behavior
No exception

### Actual Behavior
IDE Fatal error

### Steps to Reproduce

1. Place cursor after `${var.kibana_domain}` and start typing new line "\n"

**Comment by VladRassokhin** [comment]
Thanks for reporting! Seems it's related to backslash escaping. Will investigate and fix ASAP

**Comment by VladRassokhin** [comment]
Will be available in next release.
