### ISSUE TITLE
Error on Refactor-Rename

### ISSUE THREAD

**Issue by joseph-wortmann** [VladRassokhin/intellij-hcl#29]
Most recent version. Here's the error as reported by IntelliJ. Consistently reproducible.

null
java.lang.AssertionError
	at com.intellij.psi.impl.source.tree.injected.InjectedFileViewProvider.rootChanged(InjectedFileViewProvider.java:71)
	at com.intellij.psi.impl.source.PsiFileImpl.subtreeChanged(PsiFileImpl.java:440)
	at com.intellij.psi.impl.source.tree.CompositeElement.subtreeChanged(CompositeElement.java:100)
	at com.intellij.psi.impl.source.tree.ChangeUtil$1.runInner(ChangeUtil.java:177)
	at com.intellij.pom.impl.PomTransactionBase.run(PomTransactionBase.java:44)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:153)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:167)
	at com.intellij.psi.impl.source.tree.CompositeElement.replaceChild(CompositeElement.java:709)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.replaceChild(CodeEditUtil.java:204)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.replaceChildInternal(ASTDelegatePsiElement.java:388)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.replace(ASTDelegatePsiElement.java:378)
	at org.intellij.plugins.hil.psi.ILVariableManipulator.handleContentChange(ILVariableManipulator.kt:28)
	at org.intellij.plugins.hil.psi.ILVariableManipulator.handleContentChange(ILVariableManipulator.kt:22)
	at com.intellij.psi.PsiReferenceBase.handleElementRename(PsiReferenceBase.java:118)
	at com.intellij.refactoring.rename.RenameUtil.rename(RenameUtil.java:269)
	at com.intellij.refactoring.rename.RenameUtil.doRenameGenericNamedElement(RenameUtil.java:226)
	at com.intellij.refactoring.rename.RenamePsiElementProcessor.renameElement(RenamePsiElementProcessor.java:60)
	at com.intellij.refactoring.rename.RenameUtil.doRename(RenameUtil.java:187)
	at com.intellij.refactoring.rename.RenameProcessor.performRefactoring(RenameProcessor.java:413)
	at com.intellij.refactoring.BaseRefactoringProcessor$7.run(BaseRefactoringProcessor.java:470)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1009)
	at com.intellij.refactoring.BaseRefactoringProcessor.doRefactoring(BaseRefactoringProcessor.java:452)
	at com.intellij.refactoring.BaseRefactoringProcessor.access$100(BaseRefactoringProcessor.java:75)
	at com.intellij.refactoring.BaseRefactoringProcessor$3.run(BaseRefactoringProcessor.java:292)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:117)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.refactoring.BaseRefactoringProcessor.execute(BaseRefactoringProcessor.java:288)
	at com.intellij.refactoring.BaseRefactoringProcessor$5.run(BaseRefactoringProcessor.java:403)
	at com.intellij.usages.impl.UsageViewImpl$MyPerformOperationRunnable$1.run(UsageViewImpl.java:1741)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.usages.impl.UsageViewImpl$MyPerformOperationRunnable.run(UsageViewImpl.java:1737)
	at com.intellij.usages.impl.UsageViewImpl$ButtonPanel$1.actionPerformed(UsageViewImpl.java:1649)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by VladRassokhin** [comment]
Could you please provide simple code example and what expected to achieve.

**Comment by joseph-wortmann** [comment]
I was simply selecting a resource name and performing a renaming
refactoring. Any refactor of this sort should create the issue - it seemed
really consistent.

This is new to this version, BTW, and worked flawlessly before.

Regards,

Joseph Wortmann
(205) 612-3826

**Comment by VladRassokhin** [comment]
Seems problem related to interpolation language injection. So renaming would not throw exception if there not interpolations which references this resource.

@joseph-wortmann what version of IDEA (or other product) do you use?

**Comment by joseph-wortmann** [comment]
I'm on the very latest IDEAJ

Regards,

Joseph Wortmann
(205) 612-3826

**Comment by joseph-wortmann** [comment]
For Mac, if that makes a difference.

Regards,

Joseph Wortmann
(205) 612-3826

On Tue, May 17, 2016 at 12:49 PM, Joseph Wortmann <joseph.wortmann@gmail.com
> wrote:

> I'm on the very latest IDEAJ
>
> Regards,
>
> Joseph Wortmann
> (205) 612-3826
>
> On Tue, May 17, 2016 at 11:19 AM, Vladislav Rassokhin <

**Comment by VladRassokhin** [comment]
Cannot reproduce with IDEA 2016.1.3 and intellij-hcl 0.5.3 with next simple terraform config file:
```hcl
provider "aws" {
  region = ""
}

resource "aws_api_gateway_deployment" "oldname" {
  rest_api_id = ""
}

output "test-rename" {
  value = "${aws_api_gateway_deployment.oldname.stage_name}"
}
output "test-rename-2" {
  value = "${aws_api_gateway_deployment.oldname.rest_api_id}"
}
```
`oldname` seamlessly renamed from both resource definition and reference in output value interpolations.
If problem still reproducible provide some config example, please.

**Comment by VladRassokhin** [comment]
Finally found example how to reproduce that:
```hcl
provider "aws" {
  region = ""
}
resource "aws_api_gateway_deployment" "oldname" {
  rest_api_id = ""
}
output "test-rename" {
  value = <<EOF
  ${aws_api_gateway_deployment.oldname.rest_api_id}
  EOF
}
```

**Comment by VladRassokhin** [comment]
Version 0.5.4 was uploaded to plugins repository, please try it.
