### ISSUE TITLE
IDE Exception

### ISSUE THREAD

**Issue by drewsonne** [VladRassokhin/intellij-hcl#88]
I'm reporting a crash I received an error in PyCharm using the HCL plugin.

**Error message:**
```
null
```
**Details**
```
null
java.lang.NullPointerException
	at org.intellij.plugins.hcl.psi.UtilKt.isInHCLFileWithInterpolations(util.kt:73)
	at org.intellij.plugins.hcl.terraform.config.TerraformDocumentationProvider.generateDoc(TerraformDocumentationProvider.kt:35)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:144)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:659)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:656)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
	at com.intellij.util.Alarm$Request.run(Alarm.java:396)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Context**
I had created a `module {...}` resource, which required arguments and copy/pasted the required variables into a local tf file.
![pycharmcrash-details](https://cloud.githubusercontent.com/assets/233054/25843968/f9087d68-34a0-11e7-9c8c-aca3809ab1d7.png)
![pycharmcrash-summary](https://cloud.githubusercontent.com/assets/233054/25843967/f9065f06-34a0-11e7-9eb2-128588571bce.png)

**Comment by VladRassokhin** [comment]
Closing as already fixed one.
