### ISSUE TITLE
IDE Exception: com.intellij.psi.impl.source.tree.CompositeElement.getModificationCount()I

### ISSUE THREAD

**Issue by JeroenAP** [VladRassokhin/intellij-hcl#92]
I'm receiving exceptions in RubyMine from the HCL language support plugin:

```java
com.intellij.psi.impl.source.tree.CompositeElement.getModificationCount()I
java.lang.NoSuchMethodError: com.intellij.psi.impl.source.tree.CompositeElement.getModificationCount()I
	at org.intellij.plugins.hcl.psi.impl.JavaUtil.getTextFragments(JavaUtil.java:53)
	at org.intellij.plugins.hcl.psi.impl.HCLPsiImplUtils.getTextFragments(HCLPsiImplUtils.kt:194)
	at org.intellij.plugins.hcl.psi.impl.HCLPsiImplUtilJ.getTextFragments(HCLPsiImplUtilJ.java:145)
	at org.intellij.plugins.hcl.psi.impl.HCLHeredocContentImpl.getTextFragments(HCLHeredocContentImpl.java:56)
	at org.intellij.plugins.hil.ILLanguageInjector$Companion.getHCLHeredocContentInjections(ILLanguageInjector.kt:68)
	at org.intellij.plugins.hil.ILLanguageInjector$Companion.getLanguagesToInject(ILLanguageInjector.kt:46)
	at org.intellij.plugins.hil.ILLanguageInjector.getLanguagesToInject(ILLanguageInjector.kt:34)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl$PsiManagerRegisteredInjectorsAdapter.getLanguagesToInject(InjectedLanguageManagerImpl.java:494)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider$MyInjProcessor.process(InjectedPsiCachedValueProvider.java:82)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:461)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.doCompute(InjectedPsiCachedValueProvider.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.probeElementsUp(InjectedLanguageUtil.java:312)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:144)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:241)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:203)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:111)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:250)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

I'm using plugin version 0.6.3 and RubyMine 2017.2 EAP. Additional information:

RubyMine 2017.2 EAP
Build #RM-172.2656.16, built on May 31, 2017
RubyMine EAP User
Expiration date: June 30, 2017
JRE: 1.8.0_152-release-867-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by VladRassokhin** [comment]
Thanks for reporting, would be fixed in next update
